name: "test"
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build docs
        uses: rdash99/sphinx-action@master
        with:
          docs-folder: "docs/"
          build-command: "sphinx-build -M markdown . _build"
      - name: Rename index.md to repo name
        run: |
          sudo mv docs/_build/markdown/index.md docs/_build/markdown/${{ github.event.repository.name }}.md
      - name: Push to branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self # The name of the repository where you want to push the assets - can be different from the current one
          BRANCH: markdown # The branch name where you want to push the assets
          FOLDER: docs/_build/markdown # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # The secret token to push to the branch
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
      # - name: Push to gh-pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GH_TOKEN }}
      #     publish_dir: "docs/_build/html"
      #     publish_branch: gh-pages
      