name: "test"
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: rdash99/sphinx-action@master
        with:
          docs-folder: "docs/"
          build-command: "sphinx-build -M markdown . _build"
      - name: Push to branch
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          push-branch: 'markdown'
          commit-message: 'publish'
          force-add: 'true'
          files: 'docs/_build/*'
      # - name: Push to gh-pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GH_TOKEN }}
      #     publish_dir: "docs/_build/html"
      #     publish_branch: gh-pages
      